### ISSUE TITLE
登陆中心，弹幕发送等插件怎么都不见了？

### ISSUE THREAD

**Issue by 1265578519** [Bililive/www.danmuji.org#200]
登陆中心，弹幕发送等插件怎么都不见了？

**Comment by 1265578519** [comment]
https://www.danmuji.org/plugins/LoginCenter
https://www.danmuji.org/plugins/SendDanmaku
找到了！

**Comment by Elepover** [comment]
更改发生在 commit 1ef5d3f 里面

简单说，因为插件不能用 + 不维护了，所以隐藏掉

**Comment by 1265578519** [comment]
@Elepover 所有插件都正常使用，不知道你怎么说出来不能用了
正常登录使用，也可以正常发送弹幕
![image](https://user-images.githubusercontent.com/6442439/106921730-40a7a680-6747-11eb-8267-de344101201a.png)
![image](https://user-images.githubusercontent.com/6442439/106921793-54eba380-6747-11eb-9369-d5925669a223.png)

**Comment by GhostBone** [comment]
@1265578519 审题，大哥

**Comment by 1265578519** [comment]
> @1265578519 审题，大哥

什么意思？我现在正常用的

**Comment by 1265578519** [comment]
![image](https://github.com/user-attachments/assets/d9f4d9a5-f01c-424e-b689-25b4ab88f884)
1.1.1.123版本，7月9日更新的，依旧正常使用
